# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/hakve/workspace/github/exploring-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/hakve/workspace/github/exploring-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/hakve/workspace/github/exploring-cpp/CMakeFiles /mnt/c/Users/hakve/workspace/github/exploring-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/hakve/workspace/github/exploring-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named command_cli

# Build rule for target.
command_cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 command_cli
.PHONY : command_cli

# fast build rule for target.
command_cli/fast:
	$(MAKE) -f CMakeFiles/command_cli.dir/build.make CMakeFiles/command_cli.dir/build
.PHONY : command_cli/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named module

# Build rule for target.
module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module
.PHONY : module

# fast build rule for target.
module/fast:
	$(MAKE) -f CMakeFiles/module.dir/build.make CMakeFiles/module.dir/build
.PHONY : module/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/command_cli.o: src/command_cli.cpp.o

.PHONY : src/command_cli.o

# target to build an object file
src/command_cli.cpp.o:
	$(MAKE) -f CMakeFiles/command_cli.dir/build.make CMakeFiles/command_cli.dir/src/command_cli.cpp.o
.PHONY : src/command_cli.cpp.o

src/command_cli.i: src/command_cli.cpp.i

.PHONY : src/command_cli.i

# target to preprocess a source file
src/command_cli.cpp.i:
	$(MAKE) -f CMakeFiles/command_cli.dir/build.make CMakeFiles/command_cli.dir/src/command_cli.cpp.i
.PHONY : src/command_cli.cpp.i

src/command_cli.s: src/command_cli.cpp.s

.PHONY : src/command_cli.s

# target to generate assembly for a file
src/command_cli.cpp.s:
	$(MAKE) -f CMakeFiles/command_cli.dir/build.make CMakeFiles/command_cli.dir/src/command_cli.cpp.s
.PHONY : src/command_cli.cpp.s

src/module.o: src/module.cpp.o

.PHONY : src/module.o

# target to build an object file
src/module.cpp.o:
	$(MAKE) -f CMakeFiles/module.dir/build.make CMakeFiles/module.dir/src/module.cpp.o
.PHONY : src/module.cpp.o

src/module.i: src/module.cpp.i

.PHONY : src/module.i

# target to preprocess a source file
src/module.cpp.i:
	$(MAKE) -f CMakeFiles/module.dir/build.make CMakeFiles/module.dir/src/module.cpp.i
.PHONY : src/module.cpp.i

src/module.s: src/module.cpp.s

.PHONY : src/module.s

# target to generate assembly for a file
src/module.cpp.s:
	$(MAKE) -f CMakeFiles/module.dir/build.make CMakeFiles/module.dir/src/module.cpp.s
.PHONY : src/module.cpp.s

src/ui.o: src/ui.cpp.o

.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i

.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s

.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... utils"
	@echo "... command_cli"
	@echo "... ui"
	@echo "... module"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/command_cli.o"
	@echo "... src/command_cli.i"
	@echo "... src/command_cli.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

